version: '3.9'

services:
  backend:
    build:
      context: ./api
    container_name: backend
    ports:
      - '8080:8080'
    restart: always

  web:
    build:
      context: ./app
    container_name: web
    ports:
      - '3000:8080'
    depends_on:
      - backend
    restart: always
