name: CI/CD FastAPI

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          pytest backend/tests

      - name: Build Docker image
        run: |
          docker build -t gcr.io/$GCP_PROJECT_ID/todo-backend backend/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push to Google Container Registry
        run: |
          docker push gcr.io/$GCP_PROJECT_ID/todo-backend

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: todo-backend
          image: gcr.io/$GCP_PROJECT_ID/todo-backend
